#!/usr/bin/env bash

path="$HOME/Pictures/Screenshots/screen.png"
grim "$path" &&
corrupter -add 0 -bheight 20 -stdabber 10 -boffset 50 "$path" "$path" &&

swaylock -c $HOME/.config/swaylock/config &&
swaymsg "output * dpms on"
